version: "3.9"

services:
  web:
    build: .
    environment:
      - DJANGO_SUPERUSER_PASSWORD=123123
    command: >
      sh -c "pip install -r requirements.txt
      && python /code/mysite/manage.py makemigrations
      && python /code/mysite/manage.py migrate
      && python /code/mysite/manage.py createsuperuser --noinput --username msohani --email django@python.org
      || python /code/mysite/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
