version: 2.1

orbs:
  taskfile: threecomma/taskfile@0.1.0
  jq: circleci/jq@2.2.0

executors:
  machine-executor:
    machine:
      docker_layer_caching: false
      image: ubuntu-2204:2024.01.1
    
jobs:
  build_and_test:
    executor: machine-executor
    steps:
      - checkout
      - run: 
          command: |
            docker-compose up -d
            docker-compose exec web sh -c "pytest $PYTEST_ARGS"
            cd cypress && npm run test:e2e-ci

workflows:
  build_and_test:
    jobs:
      - build_and_test
