version: 2.1

orbs:
  taskfile: threecomma/taskfile@0.1.0
  node: circleci/node@5.2.0

executors:
  machine-executor:
    machine:
      docker_layer_caching: false
      image: ubuntu-2204:2024.01.1
  
commands:
  install_node_packages:
    description: Install node packages for Cypress test suite
    steps:
      - run: cd cypress
      - node/install-packages
      - run: cd ..

jobs:
  build_and_test:
    executor: machine-executor
    steps:
      - checkout
      - run: pwd && npm
      # - install_node_packages
      # - run: task tests

workflows:
  build_and_test:
    jobs:
      - build_and_test
