version: 2.1

orbs:
  taskfile: threecomma/taskfile@0.1.0
  node: circleci/node@5.2.0

executors:
  machine-executor:
    machine:
      docker_layer_caching: false
      image: ubuntu-2204:2024.01.1
    
jobs:
  build_and_test:
    executor: machine-executor
    steps:
      - checkout
      - node/install-packages
      - run: task tests

workflows:
  build_and_test:
    jobs:
      - build_and_test
