version: 2.1

orbs:
  taskfile: threecomma/taskfile@0.1.0
  jq: circleci/jq@2.2.0

executors:
  docker-executor:
    docker:
      - image: cimg/python:3.10.4
        user: root
    
jobs:
  build_and_test:
    executor: docker-executor
    steps:
      - checkout
      - run: task tests

workflows:
  build_and_test:
    jobs:
      - build_and_test
