###########################################################################
# GitHub Action Workflow
#
# Step 0: Make changes on your branch to files in admin_interface/, cypress/, django508/, .circleci or .github
#         and push changes to your remote branch.
#
# Step 1: Makes a request to the V2 CircleCI API to initiate the project,
#         which will filter based upon build_and_test to run the workflow/jobs
#          listed here:
#           build_and_test:[
#             build_and_test,
#           ]
#
#         Leverages the open source GitHub Action:
#         https://github.com/promiseofcake/circleci-trigger-action
###########################################################################
name: Build and test All on push when scripts/commands change
on:
  push:
    branches-ignore:
      - develop
      - main
      - master
      - 'release/**'
    paths:
      - 'admin_interface/**'
      - 'cypress/**'
      - 'django508/**'
      - '.circleci/**'
      - '.github/**'
jobs:
  build_and_test_all:
    runs-on: ubuntu-latest
    name: Build and Test all in CirCI
    steps:
      - uses: actions/checkout@v2
      - name: Build and Test all in CirCI
        id: curl-circle-ci
        uses: promiseofcake/circleci-trigger-action@v1
        with:
          user-token: ${{ secrets.CIRCLE_CI_V2_TOKEN }}
          project-slug: ${{ github.repository }}
          branch: ${{ (github.event_name == 'pull_request') && github.head_ref || github.ref_name }}
          payload: '{"build_and_test": true}'
